# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the client files to the working directory
COPY public/ ./public/
COPY src/ ./src/

# Build the client app
RUN npm run build